import type { Member, Milestone } from '@/types'

/**
 * 世系数据（Member 树）。
 *
 * 说明：以下为**演示用示例数据**，人名与年份均为占位，不代表真实族谱。
 * 资料确认后请整体替换本文件内容，字段结构保持不变即可。
 *
 * 结构约定：
 * - `generation` 从 1 开始，始祖为 1
 * - 子代放入父节点的 `children` 数组，递归表达世系
 * - 每位成员在各代中位置唯一，嵌套结构天然保证不重复渲染
 */
export const memberTree: Member = {
  id: 'g1-01',
  name: '始祖公',
  gender: 'M',
  generation: 1,
  birthYear: 1860,
  deathYear: 1932,
  hometown: '待补充',
  spouseName: '始祖妣',
  bio: '示例数据。始迁祖，自原籍迁居本地，垦殖立业，为家族在本地的第一代。',
  children: [
    {
      id: 'g2-01',
      name: '长房公',
      gender: 'M',
      generation: 2,
      branch: '长房',
      birthYear: 1885,
      deathYear: 1958,
      hometown: '待补充',
      spouseName: '长房妣',
      bio: '示例数据。长子，承继祖业，主持族中祭祀与田产事务。',
      children: [
        {
          id: 'g3-01',
          name: '长房长孙',
          gender: 'M',
          generation: 3,
          branch: '长房',
          birthYear: 1912,
          deathYear: 1976,
          hometown: '待补充',
          spouseName: '待补充',
          bio: '示例数据。长房长子，早年务农，后从事手工营造。',
          children: [
            {
              id: 'g4-01',
              name: '长房曾长孙',
              gender: 'M',
              generation: 4,
              branch: '长房',
              birthYear: 1940,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代长子。',
            },
            {
              id: 'g4-02',
              name: '长房曾次孙',
              gender: 'M',
              generation: 4,
              branch: '长房',
              birthYear: 1946,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代次子。',
            },
            {
              id: 'g4-03',
              name: '长房曾孙女',
              gender: 'F',
              generation: 4,
              branch: '长房',
              birthYear: 1951,
              hometown: '待补充',
              bio: '示例数据。第四代长女。',
            },
          ],
        },
        {
          id: 'g3-02',
          name: '长房次孙',
          gender: 'M',
          generation: 3,
          branch: '长房',
          birthYear: 1918,
          deathYear: 1990,
          hometown: '待补充',
          spouseName: '待补充',
          bio: '示例数据。长房次子，曾远赴外省经商。',
          children: [
            {
              id: 'g4-04',
              name: '长房曾三孙',
              gender: 'M',
              generation: 4,
              branch: '长房',
              birthYear: 1949,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代第三子。',
            },
            {
              id: 'g4-05',
              name: '长房曾四孙',
              gender: 'M',
              generation: 4,
              branch: '长房',
              birthYear: 1955,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代第四子。',
            },
          ],
        },
        {
          id: 'g3-03',
          name: '长房孙女',
          gender: 'F',
          generation: 3,
          branch: '长房',
          birthYear: 1925,
          deathYear: 2001,
          hometown: '待补充',
          bio: '示例数据。长房长女。',
        },
      ],
    },
    {
      id: 'g2-02',
      name: '次房公',
      gender: 'M',
      generation: 2,
      branch: '次房',
      birthYear: 1890,
      deathYear: 1965,
      hometown: '待补充',
      spouseName: '次房妣',
      bio: '示例数据。次子，分居村东，另立门户。',
      children: [
        {
          id: 'g3-04',
          name: '次房长孙',
          gender: 'M',
          generation: 3,
          branch: '次房',
          birthYear: 1916,
          deathYear: 1988,
          hometown: '待补充',
          spouseName: '待补充',
          bio: '示例数据。次房长子，一生执教乡塾。',
          children: [
            {
              id: 'g4-06',
              name: '次房曾长孙',
              gender: 'M',
              generation: 4,
              branch: '次房',
              birthYear: 1944,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代长孙。',
            },
            {
              id: 'g4-07',
              name: '次房曾孙女',
              gender: 'F',
              generation: 4,
              branch: '次房',
              birthYear: 1950,
              hometown: '待补充',
              bio: '示例数据。第四代长女。',
            },
          ],
        },
        {
          id: 'g3-05',
          name: '次房次孙',
          gender: 'M',
          generation: 3,
          branch: '次房',
          birthYear: 1923,
          deathYear: 1999,
          hometown: '待补充',
          spouseName: '待补充',
          bio: '示例数据。次房次子。',
          children: [
            {
              id: 'g4-08',
              name: '次房曾次孙',
              gender: 'M',
              generation: 4,
              branch: '次房',
              birthYear: 1952,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代次子。',
            },
            {
              id: 'g4-09',
              name: '次房曾三孙',
              gender: 'M',
              generation: 4,
              branch: '次房',
              birthYear: 1958,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代第三子。',
            },
            {
              id: 'g4-10',
              name: '次房曾四孙',
              gender: 'M',
              generation: 4,
              branch: '次房',
              birthYear: 1963,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代第四子。',
            },
          ],
        },
      ],
    },
    {
      id: 'g2-03',
      name: '三房公',
      gender: 'M',
      generation: 2,
      branch: '三房',
      birthYear: 1896,
      deathYear: 1971,
      hometown: '待补充',
      spouseName: '三房妣',
      bio: '示例数据。三子，迁居邻县，以贩运为业。',
      children: [
        {
          id: 'g3-06',
          name: '三房长孙',
          gender: 'M',
          generation: 3,
          branch: '三房',
          birthYear: 1921,
          deathYear: 1993,
          hometown: '待补充',
          spouseName: '待补充',
          bio: '示例数据。三房长子。',
          children: [
            {
              id: 'g4-11',
              name: '三房曾长孙',
              gender: 'M',
              generation: 4,
              branch: '三房',
              birthYear: 1948,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代长孙。',
            },
            {
              id: 'g4-12',
              name: '三房曾次孙',
              gender: 'M',
              generation: 4,
              branch: '三房',
              birthYear: 1954,
              hometown: '待补充',
              spouseName: '待补充',
              bio: '示例数据。第四代次子。',
            },
          ],
        },
        {
          id: 'g3-07',
          name: '三房孙女',
          gender: 'F',
          generation: 3,
          branch: '三房',
          birthYear: 1928,
          deathYear: 2005,
          hometown: '待补充',
          bio: '示例数据。三房长女。',
        },
      ],
    },
  ],
}

/**
 * 大事记时间线。
 * 示例数据，替换为家族真实事件即可。
 */
export const milestones: Milestone[] = [
  {
    year: '1860',
    title: '始迁祖落籍本地',
    description: '示例数据。始迁祖自原籍迁出，择地而居，为家族在本地的开端。',
  },
  {
    year: '1902',
    title: '初修族谱',
    description: '示例数据。由长房公倡议，合族集资，首度成谱。',
  },
  {
    year: '1935',
    title: '重建宗祠',
    description: '示例数据。宗祠因水患倾颓，族人合力重建，立堂号以别他支。',
  },
  {
    year: '1987',
    title: '续修族谱',
    description: '示例数据。时隔八十余年续修，补录散居外省各支。',
  },
  {
    year: '2026',
    title: '建立家族网站',
    description: '整理世系、公告与影像资料，建成家族数字门面，供族人查阅。',
  },
]
